name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_achievements: yes
          plugin_achievements_display: compact
          config_timezone: Asia/Shanghai
          config_output: svg
